TransportBundle\Entity\Transport:
    type: entity
    table: transports
    repositoryClass: TransportBundle\Repository\TransportRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        userId:
            type: smallint
        identificator:
            type: string
            unique: true
        startCity:
            type: string
        endCity:
            type: string
        startDate:
            type: datetime
        endDate:
            type: datetime
        cargo:
            type: string
        distance:
            type: integer
        weight:
            type: smallint
        damage:
            type: smallint
        burnedFuel:
            type: smallint
        fueled:
            type: smallint
        country:
            type: string
        score:
            type: smallint
        screenshot:
            type: string
            unique: true
        active:
            type: boolean

    lifecycleCallbacks: {  }
