transport:
    resource: "@TransportBundle/Resources/config/routing.yml"
    prefix:   /transport

app:
    resource: "@AppBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"

