UserBundle\Entity\ActivationCode:
    type: entity
    table: activationCode
    repositoryClass: UserBundle\Repository\ActivationCodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        role:
            type: string
            length: 255
        activationCode:
            type: integer
    lifecycleCallbacks: {  }
