login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

home:
  path: /
  defaults: { _controller: AppBundle:Default:index }

admin:
  path: /admin
  defaults: { _controller: UserBundle:Admin:show }

logout:
  path: /logout

register:
  path: /register
  defaults: { _controller: UserBundle:Registration:register }

employee_add:
  path: /employee/add
  defaults: { _controller: UserBundle:Invite:invite }

register_verification:
  path: /register/verification
  defaults: { _controller: UserBundle:InvitationCode:check }