home:
  path: /
  defaults: { _controller: AppBundle:Default:index }

login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

register:
  path: /register
  defaults: { _controller: UserBundle:Security:register }

register_verification:
  path: /register/verification
  defaults: { _controller: UserBundle:Security:registerVerification }

logout:
  path: /logout

profile:
  path: /profile
  defaults: { _controller: UserBundle:Profile:show }

employee_add:
  path: /employee/add
  defaults: { _controller: UserBundle:Security:employeeAdd }

employees_manage:
  path: /employees/manage
  defaults: { _controller: UserBundle:Security:manageEmployees }

employee_position_change:
  path: /employee/position/change/{id}
  defaults: { _controller: UserBundle:Security:changePosition }

employee_remove:
  path: /employee/remove/{id}
  defaults: { _controller: UserBundle:Security:removeUser }

driver_list:
  path: /drivers/list
  defaults: { _controller: UserBundle:Security:showDriverList }

driver_statistics:
  path: /drivers/statistics
  defaults: { _controller: UserBundle:Security:showDriverStatistics }