<?php

namespace TransportBundle\Repository;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAll() {
      return $this->getEntityManager()
          ->createQuery('SELECT t FROM TransportBundle:Transport t ORDER BY t.id ASC')
          ->getResult();
  }

  public function findAllById($id) {
    return $this->getEntityManager()
        ->createQuery("SELECT t FROM TransportBundle:Transport t WHERE t.userId = $id ORDER BY t.id ASC")
        ->getResult();
  }

  public function findNotActivated() {
    return $this->getEntityManager()
      ->createQuery('SELECT t.id, t.cargo, t.score, t.screenshot, t.startCity, t.endCity, t.endDate, u.username, u.roles, u.avatar FROM TransportBundle:Transport t, UserBundle:User u WHERE t.userId = u.id AND t.active = 0 ORDER BY t.id ASC')
      ->getResult();
  }

  public function activateById($id) {
    return $this->getEntityManager()
        ->createQuery("UPDATE TransportBundle:Transport t SET t.active = 1 WHERE t.id = $id")
        ->getResult();
  }

  public function deactivateById($id) {
    return $this->getEntityManager()
        ->createQuery("UPDATE TransportBundle:Transport t SET t.active = 0 WHERE t.id = $id")
        ->getResult();
  }

  public function removeById($id) {
    return $this->getEntityManager()
        ->createQuery("DELETE FROM TransportBundle:Transport t WHERE t.id = $id")
        ->getResult();
  }

  public function findFiveById($id)
  {
    return $this->getEntityManager()
        ->createQuery("SELECT t FROM TransportBundle:Transport t WHERE t.userId = $id AND t.active = 1 ORDER BY t.id")
        ->setMaxResults(5)
        ->getResult();
  }

  public function getFuelBurned($id)
  {
    return $this->getEntityManager()
        ->create("SELECT sum(t.fuelBurned) FROM TransportBundle:Transport t WHERE t.userId = $id")
        ->getResult();
  }
}
