<?php

namespace TransportBundle\Repository;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAll() {
    return $this->getEntityManager()
      ->createQuery('SELECT t FROM TransportBundle:Transport t ORDER BY t.id ASC')
      ->getResult();
  }

  public function findNotActivated() {
    return $this->getEntityManager()
      ->createQuery('SELECT t FROM TransportBundle:Transport t WHERE t.active = 0 ORDER BY t.id ASC')
      ->getResult();
  }
}
